spring:
  #  数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_management?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true


server:
  port: 8080
#  主键自增全局配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto